### ISSUE TITLE
Allow Gateway to run on MacOS

### ISSUE THREAD

**Issue by icraggs** [eclipse/paho.mqtt-sn.embedded-c#68]
This would be really useful!

**Comment by ty4tw** [comment]
I'm checking the .travis.yml to build with OSX.
````
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
````
 Build with OSX works well without the line **- george-edison55-precise-backports**   .
I will marge new .travis.yml to develop branch without this line.
Please modify  yml correctly?
